//! Terse constructors for writing fixtures.
//!
//! The user-facing promise of the proving grounds is "open `fixtures.rs`,
//! change the fake data". A wall of struct literals would break that promise on
//! contact, so fixtures are written with these instead.
//!
//! The city builders (`rust_city`, `node_city`, ...) write the **marker files**
//! a real project of that stack would have. That is deliberate and load-bearing:
//! `scan::detect_kind` then infers the stack by exactly the rules it uses on a
//! real folder, so `CitySpec::stack` is something the scanner *arrives at*
//! rather than something it is told.

use super::{CitySpec, FileContent, TreeSpec};
use crate::model::{CityKind, Language};
use std::ops::Range;

/// A file of a given size, filled with generated filler.
pub fn file(path: impl Into<String>, bytes: u64) -> TreeSpec {
    TreeSpec::File {
        path: path.into(),
        content: FileContent::Bulk(bytes),
    }
}

/// A file with exact contents, for when they matter.
pub fn text(path: impl Into<String>, content: impl Into<String>) -> TreeSpec {
    TreeSpec::File {
        path: path.into(),
        content: FileContent::Literal(content.into()),
    }
}

/// `count` generated files from a pattern containing `{i}`.
pub fn fill(pattern: impl Into<String>, count: usize, bytes: Range<u64>, language: Language) -> TreeSpec {
    TreeSpec::Fill {
        pattern: pattern.into(),
        count,
        bytes,
        language,
    }
}

/// A folder holding the given entries.
pub fn dir(name: impl Into<String>, children: impl IntoIterator<Item = TreeSpec>) -> TreeSpec {
    TreeSpec::Dir {
        name: name.into(),
        children: children.into_iter().collect(),
    }
}

/// A Rust project: `Cargo.toml`, a lockfile, a README.
pub fn rust_city(name: &str) -> CitySpec {
    let manifest = format!(
        "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n\
         [dependencies]\nserde = {{ version = \"1\", features = [\"derive\"] }}\n"
    );
    CitySpec::new(name, CityKind::Rust).files([
        text("Cargo.toml", manifest),
        file("Cargo.lock", 24_000),
        text("README.md", readme(name, "Rust")),
    ])
}

/// A Node project: `package.json`, a lockfile, a README.
pub fn node_city(name: &str) -> CitySpec {
    let manifest = format!(
        "{{\n  \"name\": \"{name}\",\n  \"version\": \"0.1.0\",\n  \"private\": true,\n  \
         \"scripts\": {{ \"dev\": \"vite\", \"build\": \"vite build\" }}\n}}\n"
    );
    CitySpec::new(name, CityKind::Node).files([
        text("package.json", manifest),
        file("package-lock.json", 180_000),
        text("README.md", readme(name, "Node")),
    ])
}

/// A Python project: `pyproject.toml`, a README.
pub fn python_city(name: &str) -> CitySpec {
    let manifest = format!(
        "[project]\nname = \"{name}\"\nversion = \"0.1.0\"\nrequires-python = \">=3.11\"\n"
    );
    CitySpec::new(name, CityKind::Python).files([
        text("pyproject.toml", manifest),
        text("README.md", readme(name, "Python")),
    ])
}

/// A Go project: `go.mod`, a README.
pub fn go_city(name: &str) -> CitySpec {
    let manifest = format!("module example.com/{name}\n\ngo 1.22\n");
    CitySpec::new(name, CityKind::Go).files([
        text("go.mod", manifest),
        text("README.md", readme(name, "Go")),
    ])
}

/// A project with no stack markers at all -- docs, notes, assets.
///
/// Worth having in a fixture: `CityKind::Unknown` picks a different banner
/// colour and is what any non-code folder in a real dev directory scans as.
pub fn docs_city(name: &str) -> CitySpec {
    CitySpec::new(name, CityKind::Unknown).files([text("README.md", readme(name, "documentation"))])
}

/// A project carrying markers for two stacks, which scans as `Mixed`.
pub fn mixed_city(name: &str) -> CitySpec {
    let pkg = format!("{{\n  \"name\": \"{name}-web\",\n  \"private\": true\n}}\n");
    let cargo = format!("[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n");
    CitySpec::new(name, CityKind::Mixed).files([
        text("Cargo.toml", cargo),
        text("package.json", pkg),
        text("README.md", readme(name, "Rust and Node")),
    ])
}

fn readme(name: &str, stack: &str) -> String {
    format!(
        "# {name}\n\nA {stack} project in the Proving Grounds.\n\n\
         This project is **fake**. It was generated by `kingdom-core::mockdata`\n\
         so Kingdom IDE can be exercised without touching real work.\n"
    )
}
